CREATE TABLE IF NOT EXISTS hospitals (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255) NOT NULL, capability VARCHAR(100) NOT NULL DEFAULT 'general', emergency_ready BOOLEAN NOT NULL DEFAULT TRUE, lat DECIMAL(10,7) NOT NULL, lng DECIMAL(10,7) NOT NULL, bed_status VARCHAR(50) NOT NULL DEFAULT 'unverified', phone VARCHAR(50), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_hospitals_capability_status (capability, bed_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS responders (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, unit_code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, type VARCHAR(50) NOT NULL DEFAULT 'ambulance', status VARCHAR(50) NOT NULL DEFAULT 'idle', lat DECIMAL(10,7), lng DECIMAL(10,7), heading DECIMAL(5,2) NOT NULL DEFAULT 0.0, speed_kmh DECIMAL(5,2) NOT NULL DEFAULT 0.0, battery_level INT NOT NULL DEFAULT 100, assigned_incident_id VARCHAR(64), last_beacon TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_responders_status (status), INDEX idx_responders_assignment (assigned_incident_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS incidents (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, incident_uuid VARCHAR(64) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, type VARCHAR(100) NOT NULL DEFAULT 'road_traffic_accident', status VARCHAR(50) NOT NULL DEFAULT 'reported', severity_level VARCHAR(50) NOT NULL DEFAULT 'moderate', severity_score DECIMAL(3,1) NOT NULL DEFAULT 2.5, escalation_status VARCHAR(50) NOT NULL DEFAULT 'steady', lat DECIMAL(10,7) NOT NULL, lng DECIMAL(10,7) NOT NULL, location_name VARCHAR(255), casualties_count INT NOT NULL DEFAULT 1, trapped_count INT NOT NULL DEFAULT 0, assigned_responder_id VARCHAR(50), recommended_hospital_id BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_incident_hospital FOREIGN KEY (recommended_hospital_id) REFERENCES hospitals(id), CONSTRAINT fk_incident_responder FOREIGN KEY (assigned_responder_id) REFERENCES responders(unit_code), INDEX idx_incidents_status_created (status, created_at), INDEX idx_incidents_severity_created (severity_score, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS incident_updates (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, incident_uuid VARCHAR(64) NOT NULL, source VARCHAR(50) NOT NULL, update_type VARCHAR(50) NOT NULL DEFAULT 'chat', content TEXT NOT NULL, metadata_json JSON, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_updates_incident FOREIGN KEY (incident_uuid) REFERENCES incidents(incident_uuid) ON DELETE CASCADE, INDEX idx_updates_incident_created (incident_uuid, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS scene_hazards (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, incident_uuid VARCHAR(64) NOT NULL, hazard_type VARCHAR(100) NOT NULL, severity VARCHAR(50) NOT NULL DEFAULT 'high', description TEXT, photo_url TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_hazards_incident FOREIGN KEY (incident_uuid) REFERENCES incidents(incident_uuid) ON DELETE CASCADE, INDEX idx_hazards_incident_created (incident_uuid, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
